name: CI - Build and Test with Docker

on:
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t clinic-api-test .

      - name: Run tests inside Docker container
        run: docker run --rm clinic-api-test pnpm test

      - name: Cleanup Docker image (optional)
        if: always()
        run: docker rmi clinic-api-test || true
